<!DOCTYPE html>
<html lang="en-US" style="text-align: center;">
    <meta charset="UTF-8">
    <head>
        <title>
            Admin Signup
        </title>
    </head>
    <body>
        <style>
            .btn {
                border: 2px solid black;
                background-color: white;
                color: black;
                padding: 14px 28px;
                font-size: 16px;
                cursor: pointer;

            }.sign_des {
                border-color: crimson;
                color: crimson;
            }.sign_des:hover {
                background-color: crimson;
                color: white;

            }.already {
                border-color: crimson;
                color: crimson;
            }.already:hover {
                background-color: crimson;
                color: white;

            }
            .label{
                font-family: "Comic Sans MS";
                color: white;
            }
            .split {
                height: 100%;
                width: 50%;
                position: fixed;
                z-index: 1;
                top: 0;
                overflow-x: hidden;
                padding-top: 20px;
            }

            .left {
                left: 0;
                background-color: indigo;
            }

            .right {
                right: 0;
                background-color: palevioletred;
            }

            .centered {
                position: absolute;
                top: 50%;   
                left: 50%;
                transform: translate(-50%, -50%);
                text-align: center;
            }

            .centered img {
                border-radius: 20%;
            }
        </style>

    <body>

        <div class="split left">
            <div class="centered">
                <img src="images_admin/admin_register.png">
                <h1 style="font-family: Comic Sans MS ; color: white">Welcome To SMS</h1>
                <p style="font-family: Comic Sans MS ; color: white">"Student Management System is a tool that is designed to track, maintain and manage all the data generated by a School"</p>
            </div>
        </div>

        <div class="split right">
            <div class="centered">
                <h1 style="font-family: Comic Sans MS ; color: white ; margin-top:auto"> ~ Sign Up Form </h1>
                <fieldset style="border-radius:15px ; border-color:white ; border-width:3px ; background-color: #FF7474 ; margin-bottom: 25px">
                    <legend style="font-family: Comic Sans MS ; color: white">
                        <fieldset style="border-radius:15px ; border-color:white ; border-width:3px ; background-color: crimson">Please Fill Up Data</fieldset>
                    </legend>
                            
                    <table>
                     <form action="#" method="post">
                        <td>
                            <tr>
                                    <table>
                                        <td>
                                            <div class="label" style="margin-right: 24px;">
                                                <h9>Name</h9>
                                            </div>
                                        </td>
                                        <td>
                                            <div>
                                                <input type="name" name="admin_name" id="admin_name" 
                                                    style="margin-inline-start: 7px ; padding: 7px ; margin-top: 5px;
                                                            width: 250px ; border-radius:12px ; 
                                                            outline-color: transparent ; border-color: transparent" 
                                                            placeholder="Enter Your Name" required >
                                            </div>
                                        </td>
                                    </table>

                                    <table>
                                        <td>
                                            <div class="label" style="margin-right: 8px;">
                                                <h9>Contact</h9>
                                            </div>
                                        </td>
                                        <td>
                                            <div>
                                                <input type="text" name="admin_contact" id="admin_contact" 
                                                    style="margin-inline-start: 7px ; padding: 7px ; margin-top: 5px;
                                                            width: 250px ; border-radius:12px ; 
                                                            outline-color: transparent ; border-color: transparent" 
                                                            placeholder="Active Phone No Required !" required >
                                            </div>
                                        </td>
                                    </table>

                                    <table>
                                        <td>
                                            <div class="label" style="margin-right: 27px;">
                                                <h9>Email</h9>
                                            </div>
                                        </td>
                                        <td>
                                            <div>
                                                <input type="email" name="admin_email" id="admin_email" 
                                                    style="margin-inline-start: 7px ; padding: 7px ; margin-top: 5px;
                                                            width: 250px ; border-radius:12px ; 
                                                            outline-color: transparent ; border-color: transparent" 
                                                            placeholder="you@example.com" required >
                                            </div>
                                        </td>
                                    </table>

                                    <table>
                                        <td>
                                            <div class="label">
                                                <h9>Password</h9>
                                            </div>
                                        </td>
                                        <td>
                                            <div>
                                                <input type="password" name="admin_password" id="admin_password" 
                                                    style="margin-inline-start: 7px ; padding: 7px ; margin-top: 5px;
                                                            width: 250px ; border-radius:12px ; 
                                                            outline-color: transparent ; border-color: transparent ; "  
                                                            placeholder="3+ Chars Ensure Better Security !" required>
                                            </div>
                                        </td>
                                    </table>

                                    <div style="margin-bottom: 15px">
                                        <input class="btn sign_des" type="submit" name="btnSignUp" id="btnSignUp" value="SignUp" 
                                        style="
                                        padding-left: 32px;
                                        padding-right: 32px;
                                        padding-top: 7px;
                                        padding-bottom: 7px;
                                        font-size: 17px;
                                        font-family: Comic Sans MS ; 
                                        font-weight: bold ;   
                                        border-radius: 12px ; 
                                        margin-top: 22px">
                                    </div>
                                    <div style="margin-top: 7px;">
                                        <p style="color: white ; font-family:Comic Sans MS">
                                            Please Remember Your Email & </br> Password CareFully !
                                        </p> 
                                    </div>
                                </form>
                            </tr> 
                        </td>
                     </form>
                    </table>
                </fieldset>

                <table>
                    <tr>
                        <form action="#" method="post">

                            <div style="margin-bottom: 17px">

                                <button class="btn already" name="already_acc" id="already_acc" 
                                    style="
                                    padding-left: 48px;
                                    padding-right: 48px;
                                    padding-top: 7px;
                                    padding-bottom: 7px;
                                    font-size: 17px;
                                    font-family: Comic Sans MS ; 
                                    font-weight: bold ;   
                                    border-radius: 12px ; 
                                    margin-top: 0px">Already Admin ? 
                                </button>
                            </div>
                        </form>
                    </tr>
                </table>

            </div>
        </div>
    </body>

    <?php
        include "Admin_init.php" ;
            $createTable= "CREATE TABLE IF NOT EXISTS $ADMIN(
                $ADMIN_NAME VARCHAR(20),
                $ADMIN_CONTACT VARCHAR(20) UNIQUE ,
                $ADMIN_EMAIL VARCHAR(50) PRIMARY KEY,
                $ADMIN_PASSWORD TEXT)";

            $queryExe=mysqli_query($con,$createTable);

            if(isset($_POST['btnSignUp']))
            {
                $NAME=$_POST[$ADMIN_NAME];
                $CONTACT=$_POST[$ADMIN_CONTACT];
                $EMAIL=$_POST[$ADMIN_EMAIL];
                $PASSWORD=$_POST[$ADMIN_PASSWORD];

                $sql="SELECT * FROM $ADMIN WHERE $ADMIN_EMAIL='$EMAIL' ";
                    $dbquery=mysqli_query($con,$sql);
                    $data=mysqli_num_rows($dbquery);
                    if($data){
                        ?>
                        <script type="text/javascript">
                            alert("Admin account already exist")
                            window.open("http://localhost/sms-main/Admin/admin_login.php","_self")
                        </script>
                    <?php
                    }else{
                        $insertInTable= "INSERT INTO $ADMIN VALUES('$NAME','$CONTACT','$EMAIL','$PASSWORD')";
                        $queryExe=mysqli_query($con,$insertInTable);
                        if($queryExe){
                        ?>
                            <script type="text/javascript">
                                alert("Successfully Register !")
                                window.open("http://localhost/sms-main/Admin/admin_login.php","_self")
                            </script>
                        <?php
                    }
                }
            }

            if(isset($_POST['already_acc'])){
                ?>
                    <script>
                        window.open("http://localhost/sms-main/Admin/admin_login.php","_self")
                    </script>
                <?php
            }
        ?>
    </body>
</html>